#!/usr/bin/env bash
# ============================================================================
# install-macos-style.sh — macOS-style bindings + zsh + foot scrollback
# for Omarchy (Arch Linux + Hyprland).
#
# Idempotent: safe to re-run; detects what is already applied.
#
# Usage:
#   ./install-macos-style.sh            # apply everything
#   ./install-macos-style.sh --dry-run  # show what would happen
#   ./install-macos-style.sh --no-zsh   # skip zsh / shell switch
#   ./install-macos-style.sh --no-hypr  # skip Hyprland bindings
#   ./install-macos-style.sh --no-hyprbars  # skip titlebar buttons plugin
#   ./install-macos-style.sh --no-foot  # skip foot config
# ============================================================================
set -euo pipefail

# ── defaults ────────────────────────────────────────────────────────────────
DRY_RUN=0
INSTALL_ZSH=1
APPLY_HYPR=1
APPLY_HYPRBARS=1
APPLY_FOOT=1
TS="$(date +%s)"

# ── helpers ─────────────────────────────────────────────────────────────────
info()  { printf '\033[1;34m%s\033[0m\n' "$*"; }
warn()  { printf '\033[1;33m⚠ %s\033[0m\n' "$*"; }
ok()    { printf '\033[1;32m✓ %s\033[0m\n' "$*"; }
fail()  { printf '\033[1;31m✖ %s\033[0m\n' "$*" >&2; exit 1; }
prompt(){ printf '\033[1;36m%s\033[0m ' "$*"; }

run()   { if (( DRY_RUN )); then printf '  (dry-run) %s\n' "$*"; else eval "$@"; fi; }

backup_file() {
    local f="$1"
    [[ -f "$f" ]] && cp "$f" "$f.bak.macos.${TS}"
}

# ── arg parse ───────────────────────────────────────────────────────────────
for arg in "$@"; do
    case "$arg" in
        --dry-run)  DRY_RUN=1 ;;
        --no-zsh)   INSTALL_ZSH=0 ;;
        --no-hypr)  APPLY_HYPR=0 ;;
        --no-hyprbars) APPLY_HYPRBARS=0 ;;
        --no-foot)  APPLY_FOOT=0 ;;
        -h|--help)
            sed -n '/^# Usage:/,/^# ==/{ /^# ==/d; s/^# //; s/^#//; p }' "$0"
            exit 0
            ;;
        *) fail "Unknown flag: $arg (try --help)" ;;
    esac
done

# ── preflight ───────────────────────────────────────────────────────────────
command -v omarchy  >/dev/null 2>&1 || warn "omarchy not found on PATH; continuing anyway"
[[ -d ~/.config/hypr ]] || fail "~/.config/hypr not found — not an Omarchy install?"

# ── 1. Packages ─────────────────────────────────────────────────────────────
if (( INSTALL_ZSH )); then
    info "Installing zsh, zsh-autosuggestions, wl-clipboard …"
    run "omarchy pkg add zsh zsh-autosuggestions wl-clipboard"
fi

# ── 2. .zshrc ──────────────────────────────────────────────────────────────
if (( INSTALL_ZSH )); then
    ZSH_MARKER="# ─── generated by install-macos-style.sh ───"
    if [[ -f ~/.zshrc ]] && grep -qF "$ZSH_MARKER" ~/.zshrc 2>/dev/null; then
        ok ".zshrc already contains our block — skipping write"
    else
        info "Writing ~/.zshrc (backing up existing) …"
        backup_file ~/.zshrc
        run "cat > ~/.zshrc" <<'ZSHRC_EOF'
# ─── generated by install-macos-style.sh ───
# --- Prompt: keep Omarchy's starship prompt ---
command -v starship >/dev/null && eval "$(starship init zsh)"

# --- Bash completion compatibility ---
autoload -Uz compinit && compinit
autoload -Uz bashcompinit && bashcompinit

# --- History ---
HISTSIZE=50000
SAVEHIST=50000
HISTFILE=~/.zsh_history
setopt inc_append_history
setopt share_history
setopt hist_ignore_dups
setopt hist_ignore_space

# --- Editing ---
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line

# --- Key bindings (zsh omits these; bash/readline has them) ---
bindkey '^[[3~'   delete-char         # Delete (forward)
bindkey '^[[H'    beginning-of-line   # Home
bindkey '^[[F'    end-of-line         # End
bindkey '^[OH'    beginning-of-line   # Home (application mode)
bindkey '^[OF'    end-of-line         # End (application mode)
bindkey '^[[1;3D' backward-word       # Alt+Left
bindkey '^[[1;3C' forward-word        # Alt+Right
bindkey '^[[1;5D' backward-word       # Ctrl+Left
bindkey '^[[1;5C' forward-word        # Ctrl+Right

# --- fzf (if installed) ---
command -v fzf >/dev/null && {
  source <(fzf --zsh)
}

# --- zsh-autosuggestions (if installed) ---
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null

alias ls='ls --color=auto'
alias ll='ls -lah --color=auto'
alias grep='grep --color=auto'
ZSHRC_EOF
        ok "~/.zshrc written"
    fi
fi

# ── 3. Default shell ───────────────────────────────────────────────────────
if (( INSTALL_ZSH )); then
    current_shell=$(getent passwd "$USER" | cut -d: -f7)
    if [[ "$current_shell" == */zsh ]]; then
        ok "Default shell already zsh — skipping chsh"
    else
        info "Changing login shell to /bin/zsh (will prompt for password) …"
        run 'chsh -s /bin/zsh'
        ok "Login shell changed — new terminals will start zsh"
    fi
fi

# ── 4. Hyprland bindings ───────────────────────────────────────────────────
HYPR_BINDINGS=~/.config/hypr/bindings.lua
HYPR_MARKER="macOS-style bindings (ALT ~= Cmd) -- BEGIN"

if (( APPLY_HYPR )); then
    if [[ -f "$HYPR_BINDINGS" ]] && grep -qF "$HYPR_MARKER" "$HYPR_BINDINGS" 2>/dev/null; then
        ok "Hyprland bindings already applied — skipping"
    else
        info "Appending macOS + thumb-button bindings to bindings.lua …"
        backup_file "$HYPR_BINDINGS"
        run "cat >> '$HYPR_BINDINGS'" <<'HYPR_EOF'

-- ============================================================================
-- macOS-style bindings (ALT ~= Cmd) -- BEGIN
-- Generated by install-macos-style.sh. See macos-style-bindings.md for docs.
-- ============================================================================
local function send_shortcut_once(mods, key)
  return function()
    hl.dispatch(hl.dsp.send_key_state({ mods = mods, key = key, state = "down" }))
    hl.timer(function()
      hl.dispatch(hl.dsp.send_key_state({ mods = mods, key = key, state = "up" }))
    end, { timeout = 50, type = "oneshot" })
  end
end

local function active_window_is_terminal()
  local window = hl.get_active_window()
  if not window then return false end
  for _, tag in ipairs(window.tags or {}) do
    if tag:gsub("%*$", "") == "terminal" then return true end
  end
  return false
end

o.bind("ALT + C", "Universal copy (macOS)", function()
  if active_window_is_terminal() then
    send_shortcut_once("CTRL", "Insert")()
  else
    send_shortcut_once("CTRL", "C")()
  end
end)

o.bind("ALT + V", "Universal paste (macOS)", function()
  if active_window_is_terminal() then
    send_shortcut_once("SHIFT", "Insert")()
  else
    send_shortcut_once("CTRL", "V")()
  end
end)

o.bind("ALT + X", "Universal cut (macOS)", send_shortcut_once("CTRL", "X"))

o.bind("ALT + A", "Select all (macOS)", function()
  if active_window_is_terminal() then
    -- foot [key-bindings] pipe-scrollback => wl-copy (see foot.ini).
    -- foot has no native select-all; this copies whole scrollback.
    send_shortcut_once("ALT", "A")()
  else
    send_shortcut_once("CTRL", "A")()
  end
end)

o.bind("ALT + Z", "Undo (macOS)", send_shortcut_once("CTRL", "Z"))

o.bind("ALT + Q", "Quit app (macOS)", function()
  if active_window_is_terminal() then
    hl.dispatch(hl.dsp.window.close())
  else
    send_shortcut_once("CTRL", "Q")()
  end
end)

o.bind("ALT + F", "Full screen (macOS)", hl.dsp.window.fullscreen({ mode = "maximized" }))
o.bind("ALT + SHIFT + F", "True fullscreen (macOS)", hl.dsp.window.fullscreen({ mode = "fullscreen" }))
o.bind("ALT + W", "Close window (macOS)", hl.dsp.window.close())
o.bind("ALT + SPACE", "Omarchy menu (macOS)", "omarchy-menu toggle")

-- Drag window with Alt+Left button (mirrors SUPER+Left). Alt+Right = resize.
o.bind("ALT + mouse:272", "Move window (macOS)", hl.dsp.window.drag(), { mouse = true })
o.bind("ALT + mouse:273", "Resize window (macOS)", hl.dsp.window.resize(), { mouse = true })
-- ============================================================================
-- macOS-style bindings -- END
-- ============================================================================

-- ============================================================================
-- Thumb-button tab switching -- BEGIN
-- mouse:275 = BTN_SIDE (thumb-back), mouse:276 = BTN_EXTRA (thumb-forward).
-- If buttons act reversed, swap 275 <-> 276 below.
-- ============================================================================
o.bind("mouse:275", "Next browser tab (Ctrl+Tab)", send_shortcut_once("CTRL", "TAB"), { mouse = true })
o.bind("mouse:276", "Previous browser tab (Ctrl+Shift+Tab)", send_shortcut_once("CTRL,SHIFT", "TAB"), { mouse = true })
-- ============================================================================
-- Thumb-button tab switching -- END
-- ============================================================================
HYPR_EOF
        ok "Hyprland bindings appended"
    fi
fi

# ── 4b. Hyprbars titlebar buttons ───────────────────────────────────────────
HYPRBARS_MARKER="Titlebar buttons (hyprbars) -- BEGIN"
HYPRBARS_PLUGIN_SO="/var/cache/hyprpm/ppp/hyprland-plugins/hyprbars.so"

if (( APPLY_HYPRBARS )); then
    if [[ -f "$HYPR_BINDINGS" ]] && grep -qF "$HYPRBARS_MARKER" "$HYPR_BINDINGS" 2>/dev/null; then
        ok "Titlebar buttons already applied (bindings.lua) — skipping"
    else
        info "Setting up hyprbars titlebar buttons (close/minimize/maximize) …"

        # 4b-i. Install + enable the hyprbars Hyprland plugin (builds from
        # source; needs git + cmake + network the first time).
        if hyprctl plugin list 2>/dev/null | grep -q hyprbars; then
            ok "hyprbars plugin already loaded"
        elif command -v hyprpm >/dev/null 2>&1; then
            info "Installing hyprland-plugins (hyprbars) via hyprpm …"
            run "hyprpm update || true"
            run "echo | hyprpm add https://github.com/hyprwm/hyprland-plugins"
            run "hyprpm enable hyprbars"
            run "hyprctl plugin list | grep -q hyprbars || hyprpm reload"
        else
            warn "hyprpm not found — skipping hyprbars install"
        fi

        # 4b-ii. Append the titlebar buttons config if not present.
        if [[ -f "$HYPR_BINDINGS" ]] && grep -qF "$HYPRBARS_MARKER" "$HYPR_BINDINGS" 2>/dev/null; then
            ok "Titlebar buttons config already in bindings.lua"
        else
            backup_file "$HYPR_BINDINGS"
            run "cat >> '$HYPR_BINDINGS'" <<'HYPRBARS_EOF'
-- ============================================================================
-- Titlebar buttons (hyprbars) -- BEGIN
-- macOS-style close / minimize / maximize buttons on every window.
-- Requires the hyprbars plugin (install: hyprpm add https://github.com/hyprwm/
-- hyprland-plugins && hyprpm enable hyprbars). Minimize is emulated: Hyprland
-- has no true minimize, so the window is parked on a hidden "minimized"
-- special workspace (ALT+M shows/hides it).
-- ============================================================================
hl.plugin.load("/var/cache/hyprpm/ppp/hyprland-plugins/hyprbars.so")

local hyprbars_loaded = false
for _, p in ipairs(hl.get_loaded_plugins() or {}) do
  if p.name == "hyprbars" then
    hyprbars_loaded = true
    break
  end
end

if hyprbars_loaded then
  hl.config({
    plugin = {
      hyprbars = {
        bar_height = 22,
        bar_padding = 7,
        bar_button_padding = 5,
        bar_color = "rgba(24283bdd)",
        col = { text = "rgb(a9b1d6)" },
        bar_text_size = 11,
        bar_text_font = "sans",
        bar_text_align = "left",
        bar_buttons_alignment = "left",
        bar_precedence_over_border = true,
        icon_on_hover = true,
        on_double_click = "hyprctl dispatch 'hl.dsp.window.fullscreen({ mode = \"maximized\", action = \"toggle\" })'",
      },
    },
  })

  local function hb_button(bg, fg, icon, cmd)
    hl.plugin.hyprbars.add_button({
      bg_color = bg,
      fg_color = fg,
      size = 11,
      icon = icon,
      action = "hyprctl dispatch '" .. cmd .. "'",
    })
  end

  -- Left-to-right: close, minimize, maximize (macOS traffic lights).
  hb_button("rgb(f7768e)", "rgb(1a1b26)", "×", "hl.dsp.window.close()")
  hb_button("rgb(e0af68)", "rgb(1a1b26)", "–", 'hl.dsp.window.move({ workspace = "special:minimized", follow = false })')
  hb_button("rgb(9ece6a)", "rgb(1a1b26)", "+", 'hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" })')
end

-- Show/hide the "minimized" special workspace (restore minimized windows).
o.bind("ALT + M", "Restore minimized windows (macOS)", hl.dsp.workspace.toggle_special("minimized"))
-- ============================================================================
-- Titlebar buttons (hyprbars) -- END
-- ============================================================================
HYPRBARS_EOF
            ok "Titlebar buttons config appended"
        fi
    fi
fi

# ── 5. Foot config ─────────────────────────────────────────────────────────
FOOT_INI=~/.config/foot/foot.ini
FOOT_PIPE_MARKER="pipe-scrollback=.*Mod1"
FOOT_ALTSHELL_MARKER="shell=/bin/zsh"

if (( APPLY_FOOT )); then
    if [[ ! -f "$FOOT_INI" ]]; then
        warn "foot.ini not found — skipping foot config"
    else
        backup_file "$FOOT_INI"

        # 5a. Add shell=/bin/zsh to [main] if missing
        if grep -qE "$FOOT_ALTSHELL_MARKER" "$FOOT_INI"; then
            ok "foot shell=/bin/zsh already present"
        else
            info "Inserting shell=/bin/zsh into foot.ini [main] …"
            run "sed -i '/^\[main\]/a shell=/bin/zsh' '$FOOT_INI'"
            ok "shell=/bin/zsh inserted"
        fi

        # 5b. Add pipe-scrollback Alt+A under [key-bindings] if missing
        if grep -qE "$FOOT_PIPE_MARKER" "$FOOT_INI"; then
            ok "foot Alt+A pipe-scrollback already present"
        else
            info "Inserting pipe-scrollback Alt+A into foot.ini [key-bindings] …"
            run "sed -i '/clipboard-paste=Shift+Insert Control+Shift+v XF86Paste/a pipe-scrollback=[sh -c \"wl-copy\"] Mod1+a' '$FOOT_INI'"
            ok "pipe-scrollback added"
        fi
    fi
fi

# ── 6. Validate ────────────────────────────────────────────────────────────
info "Validating …"

if (( APPLY_HYPR )) && command -v hyprctl >/dev/null 2>&1; then
    run 'hyprctl reload'
    sleep 0.5
    if hyprctl configerrors 2>/dev/null | grep -qiE 'error'; then
        warn "Hyprland reports config errors — run: hyprctl configerrors"
    else
        ok "Hyprland config OK"
    fi
fi

if (( APPLY_FOOT )) && command -v foot >/dev/null 2>&1; then
    if foot --config="$FOOT_INI" --check-config >/dev/null 2>&1; then
        ok "foot config OK"
    else
        warn "foot config has errors — run: foot --config=$FOOT_INI --check-config"
    fi
fi

# ── done ────────────────────────────────────────────────────────────────────
echo ""
ok "All done. Restart your terminal for zsh + autosuggestions."
ok "New foot windows pick up the Alt+A scrollback binding."
echo ""
echo "Full paths:"
echo "  Bindings:   $HYPR_BINDINGS"
echo "  Foot:       $FOOT_INI"
echo "  zsh:        ~/.zshrc"
echo "  hyprbars:   $HYPRBARS_PLUGIN_SO"
echo "  Backups:    ~/.config/hypr/bindings.lua.bak.macos.*"
echo "              ~/.config/hypr/bindings.lua.bak.hyprbars.*"
echo "              ~/.config/foot/foot.ini.bak.macos.*"
echo ""
echo "hyprbars note: rebuild the plugin after Hyprland upgrades with:"
echo "  hyprpm update"
